### ISSUE TITLE
More accurate handling of optional context variables and registers

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#244]
### Problem
Currently optional values are not fully supported, however this is required for `getVar` and `box.R3[T]` operations.
The way it works now is based on an ad-hoc rule which recognizes expressions of the form `box.R3[Int].get` and `getVar[Array[Byte]](1).get`.
However, if we use `val` declaration `val x = getVar[Array[Byte]](1); x.get` which is equivalent, the rule will not work, so this script will result in compiler error, but it shouldn't.

In particular `isDefined` currently is not implemented at all, so the solution below will solve this as well.

### Solution
1. `ExtractRegisterAs` should be changed to return `Option[V]` (something like `extends Extract[SOption[V]] with NotReadyValue[SOption[V]]`)
2. The same change have to be done for TaggedVariable
3. Add new IR nodes `OptionGet`, `OptionIsDefined`

**Comment by greenhat** [comment]
@ergomorphic When `TaggedVariable` extends `NotReadyValue[SOption[V]]` code like 
`OUTPUTS.map(fun (out: Box) = { out.value >= 10 })` stops working cause `out` is tagged var and "becomes" optional which is not appropriate here. Looks like we need `GetVar` IR node for `getVar` function instead of translating it into tagged var like we do it now. So we leave `TaggedVariable` unchanged.

**Comment by ergomorphic** [comment]
@greenhat yes, that is right, even semantically they are very different.
