### ISSUE TITLE
Implement modular arithmetic operations

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#327]
UPD[@aslesarenko]

- [ ] Add test to SigmaDslSpecification
- [ ] make sure serialization is tested (see TODO v6.0 in code)

**Comment by greenhat** [comment]
@kushti @ergomorphic I assume we are going to use the following syntax in ErgoScript (parsed into IR nodes): 
`a % q` -> `ModQ(a, q)`
`(a + b) % q` -> `PlusModQ(a, b, q)`
`(a - b) % q` -> ` MinusModQ(a, b, q)`

**Comment by ergomorphic** [comment]
a.plusModQ(b)

**Comment by greenhat** [comment]
@ergomorphic I'm not sure I get how "`q` is assumed". Where/when do we get `q`? 
Or is `ModQ` will be a new type? Like:
```
val ma = ModQ(a, q)
ma.plusModQ(c)
```

**Comment by kushti** [comment]
@greenhat @ergomorphic 

1. I propose to use "mod q" instead of "% q", as semantics of cryptographic "mod" differs from "%" in popular programming languages for negative numbers.
2. "q" is a global constant (order of only one cryptographically strong group we are using). So we may assume it is globally and implicitly imported everywhere. 
3. Result of all mod operators is of type of the (256-bit) big integer we already have.
