### ISSUE TITLE
Elliptic curve

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/sigmastate-interpreter#65]
- [x] Choose concrete curve
- [x] Check DDH
- [ ] Points serialization
- [ ] Insecure Fiat-shamir

**Comment by kushti** [comment]
https://datatracker.ietf.org/doc/rfc8235/
https://tools.ietf.org/html/rfc8032

**Comment by ra3dnr** [comment]
Current understanding of DDH for secp384r1:
1. Group is of prime order - good
2. In order to solve DDH one usually constructs pairing. Usual technique requires working with the field F_{p^k}. k is embedding degree. p is 385 bit. My estimate on min(k) is 11466 times factor of 371-bit number, which for sure does not have factors less than 295e6 (the real value is significantly higher judging by probabilistic algorithms). Hence embedding degree looks large enough to prevent pairing-based attacks, unless other efficient algorithm is known.
