### ISSUE TITLE
Make IRContext memory-bound. 

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#688]
ErgoInterpreter has an IRContext instance , and it seems unbounded memory consumption can happen inside it, see e.g. https://github.com/ergoplatform/ergo/issues/1189 . 

However, this is not documented, and we can't expect even that client applications will properly clear memory. Exposing entities which can not live for long time is also a sign of insecure and bad design.

I think instead of IRContext, context settings should be passed to an interpreter, and a particular setting should set memory limit for internal caches. A default value should be set in order to be good for most of imaginable applications.

**Comment by aslesarenko** [comment]
This cannot be encapsulated inside IRContext. However, IRContext can be recycled automatically by Interpreter (both prover and verifier). 

IRContext should be removed from Interpreter API and be used internally as it is appropriate.

**Comment by kushti** [comment]
> This cannot be encapsulated inside IRContext. However, IRContext can be recycled automatically by Interpreter (both prover and verifier).

What can not be encapsulalted inside IRContext? 

> 
> IRContext should be removed from Interpreter API and be used internally as it is appropriate.

Yes, as an input IRContext is  simply confusing.

**Comment by aslesarenko** [comment]
@kushti The implementation of this issue in a principled way requires many changes and doesn't look simple (as can be seen in #692). 
I don't think it worth further efforts, since IRContext will be completely removed in v5.0.
I cherry-picked optimization changes into #693. 
It is ready for review and merging. 
All ergo-unit-tests and spam-tests pass. 
Let's close this issue.
