### ISSUE TITLE
Consider limitations of a deserialized script

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#81]
A deserialized script probably could not contain following nodes:

    Inputs
    Outputs
    Self
    Height
    LastBlockUtxoRootHash
    TaggedVariable[_]

as this nodes are to be rewritten in the same bottom-up rewrite, which is to be executed once. 

Is this limitation serious? Should we do something with it, or just document it?

**Comment by ergomorphic** [comment]
@kushti This is not a limitations but rather a design choice. 
This context dependent variables can be substituted during compilation. 
The same way currently we have function `compile(env, codeText)` we can have `compileInContext(env, context, codeText)`. 
This new function should have additional phase, which will roughly do elimination of context-dependent variables.
This step is currently is [part](https://github.com/ScorexFoundation/sigmastate-interpreter/blob/master/src/main/scala/sigmastate/interpreter/Interpreter.scala#L137) of `reduceToCrypto`.
It can be moved or copied to `compileInContext` depending on what we want.
So, yes we can do context-dependent compilation, but this moves us further from code-sharing approach, because each script compiled with `compileInContext` is strictly bound to the specific state (context).

**Comment by kushti** [comment]
In current design, serialized script can contain anything but Deserialize
